export type DocStatus = "LIVE" | "PARTIAL" | "PLANNED" | "DEFERRED";

export type DocPage = {
  slug: string;
  title: string;
  summary: string;
  status?: DocStatus;
  body: string[];
  bullets?: string[];
  diagram?: string;
};

export type DocGroup = { title: string; pages: DocPage[] };

const page = (slug: string, title: string, summary: string, body: string[], options: Omit<DocPage, "slug" | "title" | "summary" | "body"> = {}): DocPage => ({ slug, title, summary, body, ...options });

export const DOC_GROUPS: DocGroup[] = [
  {
    title: "Introduction",
    pages: [
      page("", "Paymod Documentation", "Give agents money. Keep the authority.", [
        "Paymod gives autonomous software isolated wallets and programmable spending authority without giving agents unrestricted control over money. Paymod is a policy and approval framework, not wallet infrastructure it builds itself: agent wallets are provisioned on Circle's Developer-Controlled Wallets, and Paymod's own product is the deterministic policy, human approval and audit trail layered in front of that infrastructure.",
        "The financial platform currently provides isolated Agent Wallets, deterministic policy, Financial Intents, Circle-backed settlement, transfer approvals through Telegram, x402 payments, REST, SDK and MCP integrations and an append-only audit trail. Paymod Code is a separate developer product built alongside it.",
      ], { status: "LIVE", diagram: "Agent\n  ↓\nFinancial Intent\n  ↓\nPaymod Policy\n  ↓\nALLOW / REQUIRE_APPROVAL / DENY\n  ↓\nExecution\n  ↓\nAgent Wallet\n  ↓\nCircle / x402" }),
      page("current-implementation", "Current Implementation", "What the repository supports today.", [
        "Agent Wallets, policies, Financial Intents, Circle-backed transfers, the dashboard, REST, SDK and MCP server are live. Transfer approvals are live through an account-linked Telegram bot. A settlement reconciler for unknown outcomes and Paymod Code usage billing are both live, not planned.",
        "x402 payment is live for an immediate allow decision. x402 approvals are partial: the intent waits and expires because the synchronous resource request cannot yet resume after human approval. Slack approvals, outbound product webhooks, an additional Stellar or Solana rail, KMS signing and the Paymod Code MCP client are not available.",
      ], { status: "LIVE", bullets: ["Agent Wallets: LIVE", "Circle-backed settlement: LIVE", "Policy engine and Financial Intents: LIVE", "Dashboard, SDK and financial MCP server: LIVE", "Telegram transfer approvals: LIVE", "Settlement reconciler for unknown outcomes: LIVE", "x402: PARTIAL, approval resumption pending", "Paymod Code extension, managed inference and usage billing: LIVE", "Stellar/Solana rail expansion, Slack approvals, webhooks: PLANNED"] }),
      page("roadmap", "Roadmap", "Accepted direction, separated from current behavior.", [
        "Planned work is kept here so it is never mistaken for an available feature. The financial platform plans x402 approval resumption, KMS-backed signing, rate limiting, an Arc rail (Circle's own settlement chain) and, longer term, additional rails beyond Circle such as Stellar or Solana, each potentially using a different custody model - the payment interface stays the same to developers regardless of which rail executes underneath.",
        "Paymod Code plans a terminal host and MCP client support for consuming third-party MCP servers. Scoped credentials and delegated authority are deferred until they receive a dedicated design.",
      ], { status: "PLANNED", bullets: ["PLANNED: x402 approval resumption", "PLANNED: Arc rail", "PLANNED: additional wallet rails (Stellar, Solana and others) beyond Circle", "PLANNED: Paymod Code terminal host and MCP client", "DEFERRED: delegated and scoped financial credentials"] }),
    ],
  },
  {
    title: "Concepts",
    pages: [
      page("concepts/agent-wallets", "Agent Wallets", "One agent. One financial boundary.", ["An Agent Wallet is an isolated wallet, provisioned on Circle's Developer-Controlled Wallets, and the permission boundary Paymod puts in front of it. It has a separate balance, credential, policy, financial activity and execution identity.", "Policy controls what an agent may spend. Wallet isolation controls which funds that agent can physically reach. A compromised wallet credential can be revoked by pausing its wallet and cannot reach another wallet."], { status: "LIVE", diagram: "Paymod Account\n│\n├── Research Agent: balance, policy, credential\n├── Deployment Agent: balance, policy, credential\n└── Trading Agent: balance, policy, credential" }),
      page("concepts/financial-intents", "Financial Intents", "Structured requests, not unrestricted signatures.", ["Agents request structured actions from Paymod instead of receiving a general transaction-signing key. Paymod evaluates the intent and executes only after authorization.", "Supported intent types are TRANSFER and X402_PAYMENT. Each stores its wallet, amount as an atomic integer string, asset, destination, network, timestamps, decision data and an idempotency key where supplied."], { status: "LIVE", diagram: "Agent wants something\n        ↓\nFinancial Intent\n        ↓\nAuthorization\n        ↓\nExecution" }),
      page("concepts/policy", "Policy", "Rules you can read out loud.", ["Policy is deterministic and evaluated in a fixed precedence order. The same Financial Intent, active policy and relevant budget state produce the same decision.", "Implemented rules cover daily and monthly budgets, per-transaction caps, asset, network, destination and action allowlists or blocklists, approval thresholds and x402 autopay caps. Time windows, vendor abstractions and arbitrary minimum values are not implemented."], { status: "LIVE", bullets: ["Amount: DAILY_LIMIT, MONTHLY_LIMIT, PER_TRANSACTION_LIMIT", "Restrictions: ASSET, NETWORK, DESTINATION and ACTION allowlists/blocklists", "Approval: APPROVAL_THRESHOLD", "x402: X402_MAX_AUTOPAY"] }),
      page("concepts/decisions", "Authorization Decisions", "Authorization is not execution.", ["Paymod returns ALLOW, REQUIRE_APPROVAL or DENY. The persisted intent uses AUTHORIZED, WAITING_APPROVAL or DENIED to represent that result before execution begins.", "ALLOW may proceed. REQUIRE_APPROVAL holds the reservation and waits for a human where that flow is available. DENY cannot be bypassed by approval. An authorized payment can still fail or become unknown downstream."], { status: "LIVE", diagram: "Policy decision: ALLOW / REQUIRE_APPROVAL / DENY\nExecution status: AUTHORIZED → PROCESSING → COMPLETED | FAILED | EXPIRED" }),
      page("concepts/approvals", "Human Approvals", "Sensitive actions return to a person.", ["A configured approval threshold turns a transfer into WAITING_APPROVAL. The dashboard creates a one-time Telegram bot link. Only that account-linked Telegram chat can approve or deny an HMAC-signed callback for the exact intent.", "Approval expires with the reservation. Approval is not financial authority: it is a human decision surface. Before settlement, Paymod reloads wallet state and policy. A new hard denial, pause or insufficient balance stops execution."], { status: "LIVE", diagram: "Agent → transfer → REQUIRE_APPROVAL → Telegram → Approve / Deny → re-check → execution" }),
      page("concepts/execution", "Execution", "Authorization is not settlement.", ["Paymod, not the agent, creates the constrained Stellar execution. The agent credential is scoped to one wallet and cannot sign arbitrary network transactions.", "Execution creates a deterministic payment identifier, records attempts and confirms the result. Confirmed settlement converts reserved budget to spend. An unknown outcome remains reserved to avoid a second payment."], { status: "LIVE" }),
      page("concepts/audit-trail", "Audit Trail", "Every decision leaves a record.", ["Paymod persists append-only audit events for account creation, wallet and credential actions, intent decisions, approvals and completed settlements. Financial Intents also persist policy trace, decision reason and settlement data.", "The dashboard Activity page answers which wallet requested an action, which decision occurred and what happened next. The current audit API is account-scoped and returns recent events."], { status: "LIVE", diagram: "Intent → Policy → Decision → Approval → Execution → Result" }),
    ],
  },
  {
    title: "Security",
    pages: [
      page("security/security-model", "Security Model", "Permission to spend is not unrestricted control of money.", ["Paymod is not the wallet infrastructure - Circle's Developer-Controlled Wallets hold and execute for each Agent Wallet, using an entity authority Paymod controls. The agent itself receives only a revocable wallet credential, never that entity authority or any direct signing power.", "Policy enforcement, reservation accounting, idempotency and audit events protect the application boundary in front of Circle's own custody. Paymod does not protect a compromised Paymod entity credential, an approved but undesirable payment or an insecure third-party agent runtime."], { status: "LIVE", diagram: "Agent → credential → Financial Intent → Policy → human or execution → Agent Wallet → Circle" }),
      page("security/wallet-isolation", "Wallet Isolation", "Contain a compromise to one balance.", ["Each Agent Wallet maps to a distinct Circle-managed wallet and balance. Credentials and policies are wallet-scoped. Pausing or archiving one wallet prevents it from executing without affecting another wallet on the account.", "Isolation does not make a leaked credential harmless: revoke or pause the affected wallet quickly, inspect its audit trail and rotate the credential."], { status: "LIVE" }),
      page("security/credentials", "Credentials and Authentication", "Different callers receive different authority.", ["Human users authenticate with an httpOnly dashboard session. Agents use a pm_live wallet credential that is shown once, stored as a hash and scoped to one wallet. Paymod Code device authorization is separate and must not be treated as a financial credential.", "Wallet credential rotation is supported by issuing another credential. A dedicated scoped-session credential model is deferred. Internal executor and relayer secrets stay server-side."], { status: "LIVE" }),
      page("security/approval-security", "Approval Security", "Approval is bound to one exact intent.", ["Telegram linking consumes a random, hashed, single-use deep-link token. Telegram webhooks require Telegram's configured secret header and callbacks carry an HMAC signature. The callback user and chat must match the account's link.", "Approvals expire, can resolve only once and are recorded with their Telegram identity. A compromised Telegram account remains a risk, so operators should disconnect it and pause affected wallets when needed."], { status: "LIVE" }),
    ],
  },
  {
    title: "Execution",
    pages: [
      page("execution/transaction-lifecycle", "Transaction Lifecycle", "From intent to settlement.", ["A transfer is authenticated, created as a Financial Intent, evaluated, budget-reserved and either denied, held for approval or authorized. A worker claims authorized transfers, rechecks fresh state, submits a deterministic payment and records settlement.", "Intent status, approval status and settlement status are distinct. A failed or unknown settlement is not a policy denial. Unknown outcomes deliberately keep budget reserved until safely resolved."], { status: "LIVE", diagram: "Intent → authentication → policy → decision → approval if needed → execution → settlement → audit" }),
      page("execution/circle", "Circle Execution", "Circle is the current execution rail.", ["Paymod currently targets Circle's Developer-Controlled Wallets and USDC configured for the wallet. Circle executes and signs; Paymod's policy engine supplies the off-chain authorization in front of it - there is no on-chain contract of Paymod's own constraining the wallet the way an earlier Stellar-based design had.", "Mainnet operation and Arc execution are not documented as live. The payment interface is chain-neutral, so a future Stellar, Solana or other rail does not change the Agent Wallet or policy model - only which infrastructure executes underneath it."], { status: "LIVE" }),
      page("execution/x402", "x402 Payments", "Agents can pay the open web.", ["POST /v1/x402/fetch retrieves a URL. If it is not paywalled, Paymod returns it directly. If it returns a supported x402 requirement, Paymod creates an X402_PAYMENT intent, evaluates policy and pays when allowed.", "x402 is not a policy bypass. Immediate ALLOW settlement is implemented and verified against the facilitator. REQUIRE_APPROVAL is partial: it parks the intent and does not yet resume the original resource request after approval."], { status: "PARTIAL", diagram: "Agent request → 402 → Financial Intent → policy → payment → retry request → resource" }),
    ],
  },
  {
    title: "Integrations",
    pages: [
      page("integrations/mcp", "MCP", "Financial tools without signing authority.", ["@paymod/mcp-server exposes paymod_get_balance, paymod_get_budget, paymod_transfer, paymod_get_request_status and paymod_pay_x402 to MCP-capable clients. Each server session uses the wallet-scoped pm_live credential supplied by that client.", "Run it locally over stdio with PAYMOD_API_KEY and PAYMOD_API_URL, or deploy Streamable HTTP mode at /mcp with Authorization: Bearer pm_live_... on every request. Paymod Code consuming third-party MCP servers is a separate planned feature."], { status: "LIVE" }),
      page("integrations/skills", "Agent Skills", "A skill surface is planned, not shipped.", ["The repository currently ships MCP tools, REST and the TypeScript SDK. It does not yet ship a standalone Paymod agent-skill package with pay, quote, refund or balance skills.", "Use MCP or the SDK today. A distribution skill is planned in the wallet build plan."], { status: "PLANNED" }),
      page("integrations/sdk", "SDK", "Typed TypeScript access.", ["@paymod/sdk exports PaymodClient. It supports getBalance, getBudget, transfer, getRequestStatus, waitForRequest and payX402. Transfer returns AUTHORIZED, WAITING_APPROVAL or DENIED.", "Amounts are atomic integer strings, decimals depend on which rail a wallet is on. Circle USDC is six decimals, so 0.25 USDC is \"250000\"."], { status: "LIVE" }),
      page("integrations/rest", "REST API", "Direct HTTP integration.", ["Financial agents use wallet credentials with POST /v1/transfers, GET /v1/intents/:id, GET /v1/budget, GET /v1/wallet/balance and POST /v1/x402/fetch. Transfer writes require Idempotency-Key.", "Dashboard sessions manage wallets, policy, credentials, audit and Telegram approval links. See the API reference for endpoint grouping and authentication."], { status: "LIVE" }),
      page("integrations/webhooks", "Webhooks", "No outbound event subscription API yet.", ["Telegram has an inbound webhook used only to receive approval commands. Paymod does not currently expose outbound product webhooks, event signatures, retries or event subscriptions for customer applications.", "Use intent polling, GET /v1/intents/:id and the audit API today."], { status: "PLANNED" }),
    ],
  },
];

export const MORE_DOC_GROUPS: DocGroup[] = [
  { title: "Guides", pages: [
    page("guides/create-agent-wallet", "Create an Agent Wallet", "Create, fund, configure and connect.", [
      "An Agent Wallet is the balance and authority boundary for one agent. Creating one provisions a real Circle-backed wallet in the same request - there is no separate browser signature or deploy step.",
      "Before the agent can spend, the wallet must be active, funded and protected by at least one wallet-scoped spending rule. An account-wide rule can narrow authority but cannot grant it by itself.",
      "The generated pm_live credential is shown once. Store it in the agent's secret manager, never in source control or a prompt transcript.",
    ], { status: "LIVE", bullets: ["Create or sign in to your Paymod account.", "Open Wallets and choose Create Agent Wallet.", "The wallet is provisioned and active immediately - no signature required.", "Fund the wallet by sending USDC to its address from its detail page.", "Add a wallet-scoped daily, monthly or per-transaction rule.", "Generate the wallet credential and save it securely.", "Connect the agent through REST, the SDK or the MCP server."] }),
    page("guides/configure-policy", "Configure Spending Rules", "Start narrow, then expand intentionally.", ["A wallet needs a wallet-scoped spending rule before it can spend. Add a DAILY_LIMIT or PER_TRANSACTION_LIMIT, then use allowlists, blocklists and APPROVAL_THRESHOLD to fit the agent's task."], { status: "LIVE" }),
    page("guides/make-payment", "Make a Payment", "Agent to intent to result.", ["Submit POST /v1/transfers with the wallet credential and Idempotency-Key. Inspect the returned intent id. AUTHORIZED settles asynchronously, WAITING_APPROVAL awaits Telegram and DENIED includes a stable reason."], { status: "LIVE" }),
    page("guides/x402-payment", "Pay for an x402 Resource", "Pay only after policy allows it.", ["Call POST /v1/x402/fetch with a URL. A non-402 response is returned directly. A supported x402 challenge becomes an X402_PAYMENT intent. Approval-required x402 requests cannot resume yet."], { status: "PARTIAL" }),
    page("guides/human-approval", "Configure Human Approval", "Connect Telegram before a high-value transfer.", ["Create an APPROVAL_THRESHOLD policy, open Dashboard Settings and connect the Telegram bot through its one-time link. When a transfer crosses the threshold, approve or deny it in the linked chat before it expires."], { status: "LIVE" }),
    page("guides/inspect-activity", "Inspect Activity", "Investigate what an agent did.", ["Use Dashboard Activity or GET /v1/audit?accountId=... for recent append-only events. Use GET /v1/intents/:id for a specific intent's decision and settlement."], { status: "LIVE" }),
  ] },
  { title: "Paymod Code", pages: [
    page("code", "Paymod Code", "A separate developer product.", ["Paymod Code is a VS Code coding-agent product that reads, edits, runs and tests local projects with multiple model providers. It shares Paymod identity and may later use financial platform actions, but its model usage is not an Agent Wallet payment today."], { status: "PARTIAL", diagram: "Paymod\n├── Financial Platform\n└── Paymod Code" }),
    page("code/getting-started", "Getting Started with Paymod Code", "Connect a local editor.", ["Install the VS Code extension, start device authorization, approve the displayed code in the dashboard and open a workspace. Current workflows focus on the extension and local agent foundation."], { status: "PARTIAL" }),
    page("code/security", "Local Execution and Security", "Workspace actions require a clear boundary.", ["Paymod Code has its own device authorization and local execution model. Do not assume its device session grants access to a financial Agent Wallet. Command and diff approval behavior follows the current extension implementation."], { status: "PARTIAL" }),
    page("code/models", "Models", "Provider support is evolving.", ["The extension has a managed inference foundation and model-provider direction. A stable, public provider and model matrix is not documented yet, so this page does not promise individual models."], { status: "PARTIAL" }),
    page("code/billing", "Usage and Billing", "Metered, reserved and settled per request.", ["Every managed (non-BYOK) inference request reserves an estimated cost against the account's Paymod Code balance before it is sent, then settles to the real usage once the provider responds. A request is refused with an insufficient-balance error rather than allowed to run over.", "This wallet-style reserve-then-settle accounting is intentionally the same shape as the financial platform's own budget reservations, just scoped to model usage instead of transfers."], { status: "LIVE" }),
    page("code/mcp", "MCP in Paymod Code", "Planned / under development.", ["This refers to Paymod Code consuming third-party MCP servers. It is distinct from Paymod exposing its own financial MCP server, which is live today."], { status: "PLANNED" }),
  ] },
  { title: "Reference", pages: [
    page("reference/financial-intent", "Financial Intent Reference", "The persisted financial request.", ["A Financial Intent has id, accountId, walletId, requestId, idempotencyKey, type, status, atomicAmount, assetCode, networkId, destination, optional purpose, decision, decisionReason, policyTrace, metadata and timestamps. TRANSFER and X402_PAYMENT are the supported types."], { status: "LIVE" }),
    page("reference/policy", "Policy Reference", "Implemented rule schema.", ["Each policy has id, accountId, optional walletId, type, config, priority and enabled. Limits use limitAtomic, approval uses thresholdAtomic, x402 uses maxAutopayAtomic and lists use values. Atomic amounts are strings, never floats."], { status: "LIVE" }),
    page("reference/decisions", "Decision Reference", "Decision, intent and settlement states.", ["Policy decisions: ALLOW, REQUIRE_APPROVAL, DENY. Approval states: PENDING, APPROVED, DENIED, EXPIRED. Intent states include PENDING, WAITING_APPROVAL, AUTHORIZED, PROCESSING, COMPLETED, DENIED, FAILED and EXPIRED. Settlement can be PREPARING, SUBMITTED, CONFIRMED, FAILED or UNKNOWN."], { status: "LIVE" }),
    page("reference/api", "REST API Reference", "Endpoint groups and authentication.", ["Auth: /v1/auth. Wallets, policies and audit: dashboard session. Agent operations: /v1/transfers, /v1/intents/:id, /v1/budget, /v1/wallet/balance and /v1/x402/fetch with a wallet credential. Telegram approval management is /v1/approvals/telegram."], { status: "LIVE" }),
    page("reference/sdk", "SDK Reference", "@paymod/sdk.", ["Construct PaymodClient with apiKey and optional baseUrl. Methods are getBalance(), getBudget(), transfer(), getRequestStatus(), waitForRequest() and payX402()."], { status: "LIVE" }),
    page("reference/mcp-tools", "MCP Tools Reference", "Exact available tools.", ["paymod_get_balance, paymod_get_budget, paymod_transfer, paymod_get_request_status and paymod_pay_x402 are registered by @paymod/mcp-server. There are no MCP refund or quote tools today."], { status: "LIVE" }),
    page("reference/webhooks", "Webhook Reference", "No customer event webhooks.", ["The only current webhook endpoint is Telegram's inbound approval callback. There are no outbound events or customer signing keys to reference."], { status: "PLANNED" }),
    page("reference/errors", "Error Reference", "Stable machine-readable failures.", ["Error codes cover credentials, account and wallet state, policy denials, approvals, settlement, budgets, x402, idempotency and validation. SDK and MCP preserve structured Paymod errors so agents can branch safely."], { status: "LIVE" }),
  ] },
];

export const ALL_DOC_GROUPS = [...DOC_GROUPS, ...MORE_DOC_GROUPS];
export const ALL_DOCS = ALL_DOC_GROUPS.flatMap((group) => group.pages);

export function findDoc(slug: string[]): DocPage | undefined {
  return ALL_DOCS.find((doc) => doc.slug === slug.join("/"));
}
